version: '3'
services:
  postgres:
    image: quay.io/redhattraining/do378-postgres:14.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
      POSTGRES_DB: testing
